name: base_module
description: "Base module"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  freezed: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
