targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          generate_for_dir:
            include:
              - lib/** # Includes services in the connector module
              - ../core/lib/**
