name: connector_module
description: "Connector module"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  get_it: ^8.0.3
  injectable: ^2.5.0
  core_module:
    path: ../core
  base_module:
    path: ../base

dev_dependencies:
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2
